name: "Validate links"

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - master

env:
  FORMAT_FILE: README.md

jobs:
  test:
    name: 'Validate links'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Deployment Workspace
        run:
          echo "DEPLOYMENT_WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Validate all links from README.md
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          config-file: '.github/configs/mlc_config.json'

